const SUPER_ADMIN = 'SUPERADMIN';
const ADMIN = 'ADMIN';
const RESTAURANT_USER = 'RESTAURANT_USER';
const RESTAURANT_MANAGER = 'RESTAURANT_MANAGER';

module.exports = {
    SUPER_ADMIN, ADMIN, RESTAURANT_USER, RESTAURANT_MANAGER
};
